### ISSUE TITLE
Precedence of `ìn` is wrong relative to `||`

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#201]
Example: `{$eval: "'a' in ['b'] || true"}` does not work...
while: `{$eval: "('a' in ['b']) || true"}` does work.

We probably need to review the precedence of the `in` operator.

**Comment by ydidwania** [comment]
Hi, I would like to work on this. I found the precedence defined [here](https://github.com/taskcluster/json-e/blob/master/src/interpreter.js#L341).
Where else should I look to understand their usage?

**Comment by djmitche** [comment]
The operators are described in the README.  I think the first step would be to write some tests to demonstrate the issue, based on jonas's examples above.  Then the solution *may* be as easy as switching the order in the precendence list you linked to.

**Comment by ydidwania** [comment]
Sorry of the delay. I was trying to figure out what sort of test to write. I tried comparing the different types of opertators. Since `in` is a relational operator resulting in a `true` or `false` value and `||` and `&&` are logical operators, `in` should have higher precedence than `||` and `&&` similar to `==` . 
[Here](https://pastebin.mozilla.org/9073650) is the test that I wrote. All of them should pass ideally. [Here](https://pastebin.mozilla.org/9073651) is the error we get for every test

**Comment by djmitche** [comment]
Those look right!  Note that in `json-e` the tests are all in `specification.yml` in the root of the repository, rather than being Python functions as you've written them.

**Comment by ydidwania** [comment]
I had run `yarn test` once or maybe twice. I was trying to find where all of those tests were located :)
Thanks though. Should I add those three test cases as it is under `expression language - in operator
` section?

**Comment by djmitche** [comment]
Yes, that sounds good.
