### ISSUE TITLE
How to escape $ in string interpolation? want to output "$12" from "$${price}"

### ISSUE THREAD

**Issue by ericfong** [taskcluster/json-e#274]
Hi, 

I would like to output "$12" from "$${price}"

but 
```
"$${price}" => "${price}"
"\\$${price}" => "\${price}"
```

How can I escape $ that right next to ${}?

I know I can 
```
"$ ${price}" => "$ 12"
```
but price and $ sign will have a space

And I found that I can
```
"${'$'}${item.price}" => "$12"
```
It look like very hacky to me

**Comment by djmitche** [comment]
Here's a slightly less-hacky way to do it: [`"${'$' + str(price)}"`](https://taskcluster.github.io/json-e/#Playground/%7Bprice%3A%2010%7D&%22%24%7B'%24'%20%2B%20str(price)%7D%22).

But you're right, [this progression](https://taskcluster.github.io/json-e/#Playground/%7Bprice%3A%2010%7D&%5B%0A%22%24%7Bprice%7D%22%2C%0A%22%24%24%7Bprice%7D%22%2C%0A%22%24%24%24%7Bprice%7D%22%2C%0A%22%24%24%24%24%7Bprice%7D%22%2C%0A%5D) is not great.  That said, the library's compatibility guarantees require that we keep that functionality or bump the major version of the library, and since there's a reasonable workaround I don't think this is worth a breaking change.

If there's a sensible syntax that's currently invalid which could be redefined to mean what you would like, we could consider adding it.

**Comment by ericfong** [comment]
Thanks 

I think [`"${'$' + str(price)}"`](https://taskcluster.github.io/json-e/#Playground/%7Bprice%3A%2010%7D&%22%24%7B'%24'%20%2B%20str(price)%7D%22) is good enough.

I think we better add this into [String Interpolation Doc](https://taskcluster.github.io/json-e/#Language/string-interpolation)

**Comment by djmitche** [comment]
That's a good point -- do you want to make a pull request to add that to the docs?
