### ISSUE TITLE
syntax for array access and slicing

### ISSUE THREAD

**Issue by hammad13060** [taskcluster/json-e#8]
@jonasfj -> I am thinking of this kind of syntax

```javascript
var context = {key: [1,2,3,4,5]};
var template = {
a: '${ $key(0) }',
b: '${ $key(1) }',
c: {$eval: '$key(0,2)'}
};

result = {a: '1' b: '2',c: [1, 2]};
```

**Comment by jonasfj** [comment]
Why `$key` ?

Also why paranthesis instead of brackets... ie `a: '${key[0]}'`.
Both: javascript, java, c/c++, c#, rust, python, golang, and many more uses breakets `[]` of array access, so that's probably the expected syntax.

**Comment by hammad13060** [comment]
I think we are sticking with safeEval for expression evaluation, it supports bracket syntax for index access, but it doesn't support slicing like this ```[begin:end]```, so I thought we can have ```$key``` syntax, which if supplied one arguments means array access or if supplied two args means slicing.

**Comment by jonasfj** [comment]
Oh, I think we should aim to write a custom language for this.... To ensure
security. Also it's super fun :)
Maybe we don't use pegjs as pegs can be slow... I'm guessing we could write
a letter in regex, that is easily ported, then read up one how to write
hand written parsers... Hopefully a recursive parser will do, which also
would be easy to port between JS and Python...

Just like JS/c/c++/Java/golang/etc I would say `key` is an expression,
`[x]` is an operator applied to said expression.

Den 22. jan. 2017 12.43 AM skrev "Hammad Akhtar" <notifications@github.com>:

I think we are sticking with safeEval for expression evaluation, it
supports bracket syntax for index access, but it doesn't support slicing
like this [begin:end], so I thought we can have $key syntax, which if
supplied one arguments means array access or if supplied two args means
slicing.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/taskcluster/json-e/issues/8#issuecomment-274317576>,
or mute
the thread
